//ViewEtablissement
export class Etablissement {
  anneScol!: number;
  codeEtab: string | null = null;
  libeEtab: string | null = null;
  anneDeciOuvr!: number | null;
  moisDeciOuvr!: string | null;
  libeTypeEtab!: string | null;
  libeDele!: string;
  libeGouv!: string;
  libeComm!: string;
  libeZone!: string | null;
  libeSect!: string | null;
  libeOuveEtab!: string | null;
  fraiInscParAnne!: number | null;
  fraiMensActiNorm!: number | null;
  lieuNaisFond!: string | null;
  libeGenrFond!: string | null;
  libeDiplFond!: string | null;
  libeNiveEtudFond!: string | null;
  libeSituFamiFond!: string | null;
  libeNiveEtudDire!: string | null;
  libeDiplDire!: string | null;
  libeSituFamiDire!: string | null;
  libeGradDire!: string | null;
  libeQualDire!: string | null;
  libeFoncDire!: string | null;
  anciDire!: number | null;
  codeGouv!: string | null;
  libeGenrDire!: string | null;
  libeDist!: string | null;
  nomPrenFond!: string | null;
  numePiecIden!: string | null;
  dateDemaActi!: Date | null;
  libeEtatEtab!: string | null;
  adreEtab!: string | null;
  libeCommEtab!: string | null;
  codePost!: string | null;
  nomPrenDire!: string | null;
  numeCindire!: string | null;
  dateFerm!: Date | null;
  anneFerm!: number | null;
  moisFerm!: string | null;
  quarFerm: string | null = null;
  causFerm!: string | null;
  libeTypeEtatEtab: string | null = null;
  anneecreation!: number | null;
  email!: string | null;
  tele!: string | null;
  depoCahiCharPrep: string | null = null;
  cadreinspection!: string | null;
}
